### PR TITLE
Set dynamic work types for each project. (Add installation and setup type in the backend).

### PR DESCRIPTION
**Pull request by nader77**
#325 
#335

### CODE REVIEW

**Comment by nader77** [comment]
gizra_-_tracking_form


/cc @liatsade

**Comment by nader77** [comment]
After saving the time tracking in the backend:
edit_time_tracking_07_dec_2016_-_admin-adidas_fashion-regular___productivity

**Comment by nader77** [comment]
@bricel May I merge and deploy once green ?

**Comment by liatsade** [comment]
Thanks @nader77

**Comment by nader77** [comment]
Update: Changing logic to for the app to get the list of work types from the project rate types.

**Comment by nader77** [comment]
Update:
1. Added a script to prepare the DB when imported from the database.
2. Added the "installation and setup" to the backend (Features).
3. Added the rate types for each project to the API.
4. Displaying the the issue types by project.
5. Deleted the hardcoded list of issue types.

**Comment by nader77** [comment]
Example:

"Contribution hour" project in the API:
productivity_local_api_projects_2378

"Contribution hour" project issue types in the frontend:
gizra_-_tracking_form

**Comment by nader77** [comment]
Example with added "Installation and setup":

productivity_local_api_projects_2378
gizra_-_tracking_form

**Comment by nader77** [comment]
Update: Added a wiki entry on how to add new work types (Needs admin privileges.)
https://github.com/Gizra/productivity/wiki#add-a-new-issue-type-project-rate-type

**Comment by nader77** [comment]
@bricel Ready for code review.


/cc @OritGeron @liatsade

**Comment by nader77** [comment]
@bricel ^^

**Pull request merged**
