### PR TITLE
Entity Relationships

### PR DESCRIPTION
**Pull request by bricel**
Create an entity relation graph, to see a projects structure.

### CODE REVIEW

**Comment by bricel** [comment]
Using Drush, this is the result. SVG version is still WIP.

**Comment by bricel** [comment]
@bitamar this is the WIP of the entity relations project.

**Comment by bricel** [comment]
@amitaibu - Check this out.

**Comment by bricel** [comment]
Add URL  /admin/entity-relations to see simplified version without fields.

**Comment by bricel** [comment]
entity_relations___productivity

**Comment by bricel** [comment]
Cleaner view.
entity_relations___productivity

**Comment by nader77** [comment]
@bricel Getting an error when applying module in my project:
unfpa-global_ _-bash_ _143x50

**Comment by bricel** [comment]
@nader77 looking into this, you can got to the URL to bypass this for now
entity_relations___unfpa_-_united_nations_population_fund

**Comment by bricel** [comment]
@nader77 I pushed a fix for this issue.

**Pull request merged**
