### PR TITLE
WIP: Converting special time tracking nodes to work sessions

### PR DESCRIPTION
**Pull request by bitamar**
#191

### CODE REVIEW

**Comment by bricel** [comment]
@Moo64c - Merge #252 first.

**Comment by bricel** [comment]
@Moo64c - I merged the relevant branches.

**Comment by Moo64c** [comment]
@bricel 
That's all the time I have for this today, I'll finish it this week.
I was stuck on term migration - would love to see an example. Other than the term (`field_session_type`) the migration is ready.

**Comment by bricel** [comment]
Merged into #252

**Pull request closed without merging**
