### PR TITLE
Replace login to time-tracking to Github.

### PR DESCRIPTION
**Pull request by nader77**
#169

### CODE REVIEW

**Comment by nader77** [comment]
gizra_-_login

**Comment by nader77** [comment]
GitHub app:
oauth_application_settings

**Comment by nader77** [comment]
@nirgn975 
* Add ngrok
* Create an aoo
* Copy client and secret ID.

What you need to do:
Remove code from URL.

**Comment by nader77** [comment]
@bricel This is ready, I have transferred the ownership of the GitHub application to Gizra.

Please let me know if you want me to deploy it and test it.

**Comment by bricel** [comment]
Tnk, yes you can deploy.

**Comment by nader77** [comment]
Merged.

**Pull request closed without merging**
