### PR TITLE
Fix scope variables in notifications emails.

### PR DESCRIPTION
**Pull request by nader77**
#258

### CODE REVIEW

**Comment by nader77** [comment]
Fixed:

1. The total scope notification message:
gizra_productivity

2. The specific scope notification message:
gizra_productivity

3. Base64 decoding login.

4. A notice message caused by  "Global days".

**Comment by nader77** [comment]
@amitaibu PR is ready. Please review so I can merge and deploy soon.

**Comment by amitaibu** [comment]
you probably  meant @bricel :)

**Comment by nader77** [comment]
Merged.

**Comment by nader77** [comment]
Deployed and tested.

**Pull request closed without merging**
