### PR TITLE
productivity_user: provide upgrade path for GH login

### PR DESCRIPTION
**Pull request by AronNovak**
Based on the shell script documented at: https://github.com/Gizra/productivity/issues/365#issuecomment-288953201

Still to do:
 - test it in a realistic environment, to see that existing users are able to login

#365

### CODE REVIEW

**Comment by AronNovak** [comment]
@bricel I'd like to ask you to try to login at http://ghupgr-productivity.pantheonsite.io/user , on my side, I tested and everything was fine, i was connected to my real account, not to the dummy one, I was able to see my tracking records, etc.

**Comment by bricel** [comment]
@AronNovak - Worked perfectly, Thanks.

**Comment by bricel** [comment]
Regarding the mapping list, no need to map blocked users, so we should map only:
```
344	rohan
340	Aron
332	luis
315	alvaro
260	noam
259	ryan
235	rachel
231	adam
230	david.hernandez
229	liat
225	efrat
201	yoavi
197	itamargronich
184	davidb
182	yoav
181	savyon
176	pavel
175	anatoly
4	itamar
9	nader
11	roy
14	amitai
15	brice
16	orit
22	or
```

**Comment by bricel** [comment]
Also will it be required to update emails to GH emails ?

**Comment by AronNovak** [comment]
@bricel Just implemented that only active users will be migrated, it's dynamic.
For now in my opinion it's not a must to sync emails. The module itself won't keep emails in sync, if we want to use it for various notification purpose, we can do a one-time sync now, or implement a continuous sync as well if needed.

**Comment by AronNovak** [comment]
After I did my re-check on Pantheon, it turned out that one user, yoav is not in the authmap, due to this:
missing

So Productivity does not know anything about the Github username of this user. Do you think we can treat it as normal? Or do we need to fix the data?

**Comment by bricel** [comment]
@AronNovak - That's ok for Yoav, he using standard login, so no need to migrate.

**Pull request merged**
