### PR TITLE
Add stuff to project view

### PR DESCRIPTION
**Pull request by Moo64c**
#162

### CODE REVIEW

**Comment by Moo64c** [comment]
With the table added:
selection_023
(Not ready yet for the rest)

**Comment by bricel** [comment]
@Moo64c - Is is still WIP ?

**Comment by Moo64c** [comment]
Yes -only added the table

**Comment by Moo64c** [comment]
@bricel Added the new charts.
Added a new module with that: https://www.drupal.org/project/charts
selection_047

This is now ready to be merged.

**Pull request merged**
