### PR TITLE
Behat test project types.

### PR DESCRIPTION
**Pull request by DavidBronfen**
#282

### CODE REVIEW

**Comment by DavidBronfen** [comment]
@nirgn975 Ready to review

**Comment by nirgn975** [comment]
@DavidBronfen Remove the `WIP` from the title.

**Comment by DavidBronfen** [comment]
@nirgn975  Done

**Comment by nirgn975** [comment]
@DavidBronfen Add an empty line in the end of the `projects.feature`.
When you go to `Files changed` section (in this PR) look how it mark the read arrow, it's expect for a new line and the end of the file.
behat_test_project_types__by_davidbronfen_ _pull_request__283_ _gizra_productivity

**Comment by DavidBronfen** [comment]
@nirgn975 Done.

**Pull request merged**
